services:
  db:
    image: postgres:16.3
    container_name: budget-db
    ports:
      - 5432:5432
    restart: always
    networks:
      - budget
    volumes:
      - tg_budget_data:/var/lib/postgresql/data/
      - ./logs:/app/logs
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-app
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - budget
    command: >
      bash -c "
      alembic upgrade head &&
      python Scripts/run.py"
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POLLER_REQUEST_TIMEOUT=${POLLER_REQUEST_TIMEOUT}

volumes:
  tg_budget_data:

networks:
  budget:
